// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/Aden-Q/short-url",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/shorten": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "ShortenHandler shortens a long URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "long URL",
                        "name": "longURL",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "short URL",
                        "schema": {
                            "$ref": "#/definitions/model.URL"
                        }
                    },
                    "400": {
                        "description": "Invalid URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/{shortURL}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "RedirectHandler redirects a short URL to a long URL",
                "responses": {
                    "301": {
                        "description": "long URL",
                        "schema": {
                            "$ref": "#/definitions/model.URL"
                        }
                    },
                    "400": {
                        "description": "Invalid URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "URL not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.URL": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "longURL": {
                    "type": "string"
                },
                "shortURL": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "short URL",
	Description:      "A fast URL shortener service written in Go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
