name: Auomatic version bump and changelog with cocogitto

on:
    # Runs on pushes targeting the default branch
    push:
      branches: ["main"]
  
jobs:
    cog_auto_release:
      continue-on-error: true
      runs-on: ubuntu-latest
      name: create a github release
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: Semantic versioning release
          uses: cocogitto/cocogitto-action@v3
          id: release
          with:
            release: true
            git-user: 'cocogitto[bot]'
            git-user-email: 'mycoolproject@org.org'
            check-latest-tag-only: true
  
        - name: Generate a changelog for release
          if: ${{ success() }}
          run: cog changelog --at ${{ steps.release.outputs.version }} > RELEASE_CHANGELOG.md
  
        - name: Create github release
          if: ${{ success() }}
          run: |
            gh release create \
              ${{ steps.release.outputs.version }} \
              --title ${{ steps.release.outputs.version }} \
              --notes-file RELEASE_CHANGELOG.md \
              --target main
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
        - name: no bump
          if: ${{ failure() }}
          run: echo "Skipped as no detected version bump"
