name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: release
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true

    - name: Create github release
      if: ${{ success() }}
      run: |
        gh release create \
          ${{ steps.release.outputs.new_tag }} \
          --title ${{ steps.release.outputs.new_tag }} \
          --target main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Skip github release
      if: ${{ failure() }}
      run: echo "Skipping github release"
